// Define setting for different skyrockets.
var skyrockets = [
	{
		'name' : 'rocket1',
		'outerRadius' : 100,
		'innerRadius' : 70,
		'numParticles' : 80,
		'color1' : '0,255,0',
		'color2' : '255,0,0',
		'particleRadius' : 5,
		'xFunction' : 'cos',
		'yFunction' : 'sin',
		'rocketIcon' : '\f1e2',
		'rocketIconSize' : '14px'
	},
	{
		'name' : 'rocket2',
		'outerRadius' : 50,
		'innerRadius' : 10,
		'numParticles' : 20,
		'color1' : '0,100,255',
		'color2' : '255,0,0',
    'particleRadius' : 5,
    'xFunction' : 'cos',
    'yFunction' : 'sin',
    'rocketIcon' : '\f135',
    'rocketIconSize' : '14px'
  },
	{
		'name' : 'rocket3',
		'outerRadius' : 80,
		'innerRadius' : 20,
		'numParticles' : 20,
		'color1' : '0,150,200',
		'color2' : '255,0,100',
    'particleRadius' : 5,
    'xFunction' : 'cos',
    'yFunction' : 'sin',
    'rocketIcon' : '\f077',
    'rocketIconSize' : '16px'
  },
  {
    'name' : 'rocket4',
    'outerRadius' : 30,
    'innerRadius' : 20,
    'numParticles' : 20,
    'color1' : '0,150,200',
    'color2' : '255,102,0',
    'particleRadius' : 5,
    'xFunction' : 'sin',
    'yFunction' : 'tan',
    'rocketIcon' : '\f179',
    'rocketIconSize' : '18px'
  },
  {
    'name' : 'rocket5',
    'outerRadius' : 200,
    'innerRadius' : 100,
    'numParticles' : 20,
    'color1' : '255,247,0',
    'color2' : '255,0,0',
    'particleRadius' : 5,
    'xFunction' : 'cos',
    'yFunction' : 'sin',
    'rocketIcon' : '\f17a',
    'rocketIconSize' : '14px'
  },
  {
    'name' : 'rocket6',
    'outerRadius' : 120,
    'innerRadius' : 20,
    'numParticles' : 200,
    'color1' : '255,247,0',
    'color2' : '255,0,100',
    'particleRadius' : 5,
    'xFunction' : 'cos',
    'yFunction' : 'sin',
    'rocketIcon' : '\f004',
    'rocketIconSize' : '16px'
  },
  {
    'name' : 'rocket7',
    'outerRadius' : 220,
    'innerRadius' : 40,
    'numParticles' : 320,
    'color1' : '207,3,227',
    'color2' : '0,255,43',
    'particleRadius' : 5,
    'xFunction' : 'tan',
    'yFunction' : 'cos',
    'rocketIcon' : '\f2cd',
    'rocketIconSize' : '14px'
  },  {
    'name' : 'rocket8',
    'outerRadius' : 120,
    'innerRadius' : 100,
    'numParticles' : 320,
    'color1' : '207,3,227',
    'color2' : '0,255,43',
    'particleRadius' : 5,
    'xFunction' : 'cos',
    'yFunction' : 'sin',
    'rocketIcon' : '\f0b1',
    'rocketIconSize' : '14px'
  },
];